name: Sequential
on:
  push:
jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo one
  Job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo two
  Job3:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo three
  Job4:
    runs-on: ubuntu-latest
    needs: [job2, job3]
    steps:
      - run: echo four
  Job5:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: job1
    steps:
      - run: echo five
