name: Sequential
on:
  push:
jobs:
  Job 1:
    runs-on: ubuntu-latest
    steps:
      - run: echo one
  Job 2:
    runs-on: ubuntu-latest
    steps:
      - run: echo two
  Job 3:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo three
  Job 4:
    runs-on: ubuntu-latest
    needs: [job2, job3]
    steps:
      - run: echo four
  Job 5:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: job1
    steps:
      - run: echo five
