name: Task_8
on: push
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - run: echo one
  job2:
    runs-on: windows-latest
    needs: job1
    if: ${{ false }}
    steps:
      - run: echo two
  job3:
    runs-on: ubuntu-latest
    if: always()
    needs: job2
    steps:
      - run: echo three
